# Copyright (C) 2018 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# It is expected that this include file is included by the module that
# needs dependency on this module. It updates MODULE_DEPS and MODULE_SRCDEPS
# callers variables with dependencies appropriate for this module.
#

# include common-inc.mk to set SYSCALL_SRCS and friends
include $(GET_LOCAL_DIR)/common-inc.mk

# Add dependency on syscall-stubs module. The syscall stubs have their own
# module so more than one module can depend on it, but still be compiled once.
MODULE_DEPS += \
	$(SYSCALL_MODULE) \

# Add depencency on sources (trusty-syscalls.h) generated by
# syscall-stubs module
MODULE_SRCDEPS += \
	$(SYSCALL_SRCS) \

# Add include directory
MODULE_INCLUDES += \
	$(SYSCALL_SRCS_DIR) \
